### ISSUE TITLE
Install on VSCode Server

### ISSUE THREAD

**Issue by KeithIMyers** [zxqfl/TabNine#105]
Do you think it is possible to install this on VSCodr Server if I purchase a license (https://github.com/cdr/code-server). I use a Chromebook as my primary machine and access my Linux Desktop to code on. Code Server can take standard VSCode Extensions I would need to import the extension manually. Is this possible?

Specifically, it is looking for a .VISX file

**Comment by KeithIMyers** [comment]
Update - I managed to get it working. Here are the steps I followed

1. Installed VSCode on my Laptop
2. Installed TabNine via the instructions for VSCode
3. scp'ed the ~/.vscode/extensions/tabnine.tabnine-vscode-1.3.0 directory to the server running code-server, specifically into ~/.local/share/code-server/extensions/
4. Restarted code-server
5. Open the Extensions and Disable TabNine. You will be prompted to refresh the session, go ahead and do it
6. Re-enable TabNine and restart the session

You should now be able to open a new file and enter TabNine::version" to test it

**Comment by zxqfl** [comment]
I'm glad you got it working! Thanks for leaving these instructions.

**Comment by darekdeo** [comment]
Hi,
First of all, sorry for digging. I am having problems with running TabNine extension on code-server. If I understand correctly, path done by @KeithIMyers does not solve the issue as solution seems like user workaround, this issue shouldn't be simply closed.

From what I understand:
1. @KeithIMyers had 3 devices: Chromebook, Linux desktop, laptop.
2. VSCode and TabNine have been installed on laptop
3. VSCode-server has been installed on desktop, but there were issues with installing/running TabNine
4. In order to make everything work, TabNine files were copied from laptop (running VSCode) to desktop (running VSCode-server)

As user I expect that extension installation should work just fine from VSCode-server.

It seems like currently it does install through VSCode-server, but not entirely (?), or for some reason extension does not work, but:
- in VSCode-server extensions directory: ~/.local/share/code-server/extensions/tabnine.tabnine-cscode-3.4.23, and there I have bunch of files, LICENSE, README, package.json, out/extension.js, bunch of .png, .svg. So indeed only .vsixmanifest is missing (compared to installation through VSCode)
- in VSCode-server, in extensions panel it is marked as enabled.
- After installing it through VSCode-server, there is no "initialization" running in the background, I was able to see it during installation in VSCode, but not VSCode-server

My installation info:
code-server: v3.11.1 (at the time of writing latest version available through npm, also tested on 3.5.x)
VS Code: v1.57.1
TabNine extension version: 3.5.23
