### ISSUE TITLE
The protocol documentation update for closing brackets feature

### ISSUE THREAD

**Issue by Shougo** [zxqfl/TabNine#106]
https://github.com/zxqfl/TabNine/commit/bca744fa0ccbba6e60ae092cf4a705e636e32655#diff-04c6e90faac2675aa89e2176d2eec7d8R33

It adds the feature of closing brackets for its suggestions.

But...

> The editor clients do not support this yet as it requires an upgrade to the communication protocol with TabNine; this is coming soon.

The communication protocol is not updated.

Can you update https://github.com/zxqfl/TabNine/blob/master/HowToWriteAClient.md?

**Comment by zxqfl** [comment]
This is actually supported by the current protocol, it's the purpose of the `new_suffix` and `old_suffix` fields. I added an example to the guide to clarify the purpose of these fields. Here's the example:

The behavior of autocompletion is as follows: when the user selects the result, the text before the cursor should be `old_prefix`, and it should be replaced by `new_prefix`. The text after the cursor should be `old_suffix`, and it should be replaced by `new_suffix`.

For example, suppose the current state of the editor is as follows (where \| represents the cursor):

```
if (x == |)
```

Suppose TabNine wants to suggest `if (x == 0) {`. Then the fields will be as follows:
- `old_prefix = ""`
- `new_prefix = "0) {"`
- `old_suffix = ")"` (we need to delete the closing bracket after the cursor because it's already included in `new_prefix`)
- `new_suffix = "}"` (inserting a matching closing bracket for the `{`)

After the completion is accepted, the editor will look like this:
```
if (x == 0) {|}
```

**Comment by Shougo** [comment]
Thanks!  I get it.
