### ISSUE TITLE
use local gpu

### ISSUE THREAD

**Issue by lujfsd** [zxqfl/TabNine#142]
how to use local GPU in TabNine Local Mode?

**Comment by zxqfl** [comment]
Sorry, we don't currently support using the local GPU with TabNine Local. It's added to the backlog.

**Comment by lujfsd** [comment]
Looking forward to your good news

**Comment by cameronbergh** [comment]
same <3

**Comment by happyTonakai** [comment]
Really need this feature. CPU load causes fans to make very loud noises.

**Comment by dharmeshkakadia** [comment]
Any news on this? Would be great to not have CPU fan running any time I try to type :)

**Comment by liudongxiao** [comment]
hope to support

**Comment by omerzam** [comment]
would be great to have this feature, any news?

**Comment by lujfsd** [comment]
> would be great to have this feature, any news?

no, maybe this is a complex project.

**Comment by swiknaba** [comment]
@lujfsd Tabnine actually offers GPU computation on their cloud: https://www.tabnine.com/subscribe/#cloud so it seems to me, there is existing and working code, to run Tabnine on a GPU.

I have a more than good enough GPU in my local machine, thus I'd be very interested in a feature, to use my local GPU instead of a remote server.

**Comment by alexzanderr** [comment]
why not thinking from the beginning @tabnine to make the AI computation on the user GPU or put the user into the position to choose between CPU or GPU in order to achieve the best user experience from performance point of view ??? i have a GTX 1050 on my laptop on linux and with tabnine its NOT used at all. its waste of power... my CPU is spiking all the time when i type 1 character because your great local machine learning algorithm its not executed on cuda cores (in case of nvidia), instead its executed on a poor CPU. great. thanks. i mean you train your neural nets on GPUs ... cmon guys
