### ISSUE TITLE
Type information in semantic completion

### ISSUE THREAD

**Issue by Shougo** [zxqfl/TabNine#30]
LSP semantic completion has type information.
I think it should be displayed in tabNine client.

I want to support the feature in deoplete.

**Comment by zxqfl** [comment]
TabNine will pass along the `detail`, `documentation`, `kind`, and `deprecated` fields from the LSP backend. In order to see this you will need to upgrade the protocol version to 1.0.0 (https://github.com/tbodt/deoplete-tabnine/blob/master/rplugin/python3/deoplete/sources/tabnine.py#L68). The protocol is documented at https://github.com/zxqfl/TabNine/blob/master/HowToWriteAClient.md.

**Comment by zxqfl** [comment]
In particular the `detail` field usually includes type information.

**Comment by Shougo** [comment]
Thank you for the answer.
I will add the support in deoplete-tabnine.

**Comment by Shougo** [comment]
Hi.  I have tested the protocol.  It works fine.
But some LSP use `label` as type information.
For example: `pyls`
Can you add `label` field in tabNine candidates?

**Comment by Shougo** [comment]
Thank you!

**Comment by Shougo** [comment]
Done.

https://github.com/tbodt/deoplete-tabnine/pull/12

**Comment by Shougo** [comment]
@zxqfl Another question.  semantic completion must be enabled in all files?
If I use `TabNine::sem`, it works in the buffer but in other buffers does not work.

**Comment by Shougo** [comment]
https://github.com/zxqfl/TabNine/issues/30#issuecomment-447788335

This is my fault.  Please ignore it.

**Comment by zxqfl** [comment]
Semantic completion is enabled per-language, so you should only have to type TabNine::sem once to enable it for all Python files.

Does TabNine show any message in the files where it doesn't work?
