### ISSUE TITLE
Language Server exited unexpectedly...

### ISSUE THREAD

**Issue by janbaer** [zxqfl/TabNine#54]
I just configured the sematic support for Less and Css like it was described in #25  and then I activated it.
Now I see always that the language server was exited unexpectedly. I tried to restart TabNine, but it doesn't helped. The semantic completion for HTML for example is working fine, after the language server for HTML was installed.

How can I find out what's the problem is and how could I probably solve it. Is there any log output?

**Comment by zxqfl** [comment]
The debugging capabilities aren't great at the moment. You could try running the same command as TabNine in the command line and checking that the language server starts successfully.

**Comment by janbaer** [comment]
I checked it before and the language-server had no problem to start. But maybe the problem will happen when TabNine sends some data to the language server. How could I test this?

**Comment by dotnetdanny** [comment]
Looks like I have hit this issue with C++ and cquery. Cquery runs fine in the terminal but doesn't seem to run at all under TabNine. It also doesn't seem to pick up any of my other config for cquery such as a log file when running under TabNine

**Comment by dotnetdanny** [comment]
Ok, so from looking at the fact that cquery run from terminal uses a log file (when requested) yet doesnt when run from TabNine (even though I put the command arg in the TabNine.toml file) it appears as though you cannot configure cquery via TabNine's config. 

I therefore, forked cquery and made some hard coded amendments to log files etc and rebuilt cquery, that way, TabNine would be just callinhg cquery without any args and the new defaults would output as I would expect so I can get some log file output. This turned out to be the case. It looks like TabNine isn't firing off cquery correctly using the arguments from the toml file. 

Once I started to get some log output, the following appears in the cquery log indicating that there is something TabNine is throwing at it that is making it crash. 

`( 407.576s) [stdin        ]            lsp.cc:103   | Unknown field in the header
( 407.576s) [stdin        ]            lsp.cc:188   | Failed to read JsonRpc input; exiting
( 407.576s) [stdin        ]        loguru.hpp:1767  | atexit
` 
@zxqfl, could you confirm that you're looking at this? 

I am running TabNine in Vim8 within docker, with code compiled against gcc 7.3.0

**Comment by dotnetdanny** [comment]
It also looks like one of your options files that appear in the tmp dir point at log files for stdout and stderr but nothing is ever written to them

**Comment by dotnetdanny** [comment]
This is not good at all. No response 2 weeks on from @zxqfl, this is hardly what I would call good support from a product I have purchased. I have since, found a new solution all together. I wouldn't recommend anyone use this application.

**Comment by uolot** [comment]
@dotnetdanny Yeah, sadly the author disappeared, which quite sucks for people who paid for the product. See https://github.com/zxqfl/TabNine/issues/66 and there's also another discussion but I can't find it ATM.

What's the alternative solution you use?

**Comment by dotnetdanny** [comment]
I've found code-server from codercom. It allows me to run vscode in the browser, all of my set up is within a docker container and having vscode run alongside my codebase allows me to get vscode standard intellisense for C++ whilst using docker for Mac (without having the nasty file mount / rsync issues due to the osx file mount speed problem). Now I can just run vscode hosted from within the container. 

TabNine was just a way of getting intellisense working in the terminal, but code-server now addresses all of that

**Comment by uolot** [comment]
Thanks @dotnetdanny. As someone who doesn't use VS Code, doesn't code in C++, and doesn't use OSX, I won't benefit from this solution :)

**Comment by dotnetdanny** [comment]
Ah, shame, it's a great solution. Looks like the best things in life really are free :)

**Comment by shuxiao9058** [comment]
just waiting for @zxqfl's reply.

**Comment by zxqfl** [comment]
I'm glad you found another solution. Could you please do one of the following?

1. Provide complete instructions for reproducing your issue
2. State the input sent to cquery which caused cquery to crash

**Comment by janbaer** [comment]
I just tried the autocompletion again with the newest version of TabNine and now also the support for CSS and LESS is working! Thanks for fixing it.
