### ISSUE TITLE
why is TabNine running a webserver?

### ISSUE THREAD

**Issue by thedch** [zxqfl/TabNine#81]
```
$ lsof -i | grep TabNine
TabNine   85328 daniel    3u  IPv4 0xbf52a4e236a5a90d      0t0  TCP localhost:43938 (LISTEN)
```

**Comment by zxqfl** [comment]
I assume you are using Vim or Atom? The TabNine clients for those editors are forks of YCMD clients, so TabNine emulates the YCMD protocol to provide completions. Since the protocol is JSON over HTTP, this requires listening on a port.

TabNine implements the HMAC authentication described [here](https://github.com/ycm-core/ycmd#is-hmac-auth-for-requestsresponses-really-necessary) (and does not execute remote code even from authenticated requests).
